// src/components/component-form.tsx
import Form from '@rjsf/core'
import validator from '@rjsf/validator-ajv8'
import { useMemo, useState } from 'react'

import { KeyValueField } from '~/components/jsonschema/key-value-field'
import { FormRow } from '~/components/shared/form-row'
import { Button } from '~/components/ui/button'
import { Input } from '~/components/ui/input'
import { SingleSelect } from '~/components/shared/multi-select'
import { componentService } from '~/services/data.service'

interface ComponentType {
  type: string
  typeName: string
}

interface ComponentFormValue {
  name?: string
  props?: Record<string, unknown>
  type?: string
  typeName?: string
}

const componentTypes = [
  { label: '触发器(TRIGGER)', value: 'TRIGGER' },
  { label: '数据源(SOURCE)', value: 'SOURCE' },
  { label: '下载器(DOWNLOADER)', value: 'DOWNLOADER' },
  { label: '条目文件解析(ITEM_FILE_RESOLVER)', value: 'ITEM_FILE_RESOLVER' },
  { label: '文件移动器(FILE_MOVER)', value: 'FILE_MOVER' },
  { label: '条目过滤(SOURCE_ITEM_FILTER)', value: 'SOURCE_ITEM_FILTER' },
  { label: '条目内容过滤(ITEM_CONTENT_FILTER)', value: 'ITEM_CONTENT_FILTER' },
  { label: '文件内容过滤(FILE_CONTENT_FILTER)', value: 'FILE_CONTENT_FILTER' },
  { label: '标签器(TAGGER)', value: 'TAGGER' },
  { label: '文件替换规则(FILE_REPLACEMENT_DECIDER)', value: 'FILE_REPLACEMENT_DECIDER' },
  { label: '文件检测规则(FILE_EXISTS_DETECTOR)', value: 'FILE_EXISTS_DETECTOR' },
  { label: '变量提供(VARIABLE_PROVIDER)', value: 'VARIABLE_PROVIDER' },
  { label: '变量替换(VARIABLE_REPLACER)', value: 'VARIABLE_REPLACER' },
  { label: '处理监听(PROCESS_LISTENER)', value: 'PROCESS_LISTENER' },
]

export function ComponentForm() {
  const [formData, setFormData] = useState<ComponentFormValue>({})
  const [schema, setSchema] = useState<Record<string, any>>({})
  const [uiSchema, setUiSchema] = useState<Record<string, any>>({})
  const [currentTypeComponentOptions, setCurrentTypeComponentOptions] = useState<ComponentType[]>([])

  const componentTypeOptions = useMemo(() => componentTypes, [])
  const typeNameOptions = useMemo(
    () => currentTypeComponentOptions.map((item) => ({ label: item.typeName, value: item.typeName })),
    [currentTypeComponentOptions],
  )

  const handleTypeSelected = async (type?: string) => {
    setFormData((current) => ({ ...current, type, typeName: undefined, props: undefined }))
    setSchema({})
    setUiSchema({})
    if (!type) {
      setCurrentTypeComponentOptions([])
      return
    }
    const types = await componentService.types({ type })
    setCurrentTypeComponentOptions(types.data)
  }

  const handleTypeNameSelected = async (typeName?: string) => {
    setFormData((current) => ({ ...current, typeName, props: {} }))
    if (!typeName || !formData.type) {
      return
    }
    const response = await componentService.getComponentPropSchema(formData.type, typeName)
    if (!response.data.propertySchema) {
      setSchema({})
      setUiSchema({})
      return
    }
    const nextSchema = response.data.propertySchema
    setSchema(nextSchema)

    const resultSet: Record<string, { 'ui:field': string }> = {}
    for (const key in nextSchema.properties ?? {}) {
      const property = nextSchema.properties[key]
      if (property.type === 'object' && property.additionalProperties && property.additionalProperties.type === 'string') {
        resultSet[key] = { 'ui:field': 'keyValueField' }
      }
    }

    const merged = {
      ...resultSet,
      ...Object.keys(response.data.uiSchema ?? {}).reduce<Record<string, any>>((acc, key) => {
        acc[key] = { ...resultSet[key], ...response.data.uiSchema[key] }
        return acc
      }, {}),
    }
    setUiSchema(merged)
  }

  return (
    <div className="space-y-4">
      <div className="grid gap-4">
        <FormRow label="组件类型" required>
          <SingleSelect options={componentTypeOptions} value={formData.type} onChange={handleTypeSelected} placeholder="选择组件类型" />
        </FormRow>
        <FormRow label="组件类型名称" required>
          <SingleSelect options={typeNameOptions} value={formData.typeName} onChange={handleTypeNameSelected} placeholder="先选择组件类型" disabled={!formData.type} />
        </FormRow>
        <FormRow label="组件名称">
          <Input value={formData.name ?? ''} onChange={(event) => setFormData((current) => ({ ...current, name: event.target.value }))} />
        </FormRow>
        <FormRow label="组件属性">
          {Object.keys(schema).length > 0 ? (
            <Form
              schema={schema}
              uiSchema={uiSchema}
              formData={formData.props}
              validator={validator}
              templates={{ ButtonTemplates: { SubmitButton: () => null } }}
              fields={{ keyValueField: KeyValueField }}
              onChange={(event) => setFormData((current) => ({ ...current, props: event.formData as Record<string, unknown> }))}
            />
          ) : (
            <div className="rounded-md border border-dashed p-4 text-sm text-muted-foreground">暂无 schema</div>
          )}
        </FormRow>
      </div>
      <Button type="button" onClick={() => console.log('提交数据', formData)}>
        确定
      </Button>
    </div>
  )
}

// src/components/ComponentForm.vue
<template>
  <el-form :model="formData" label-width="auto" style="max-width: 600px">
    <el-form-item label="组件类型" required>
      <el-select v-model="formData.type" placeholder="选择组件类型" @change="handleTypeSelected" filterable>
        <el-option
            v-for="item in componentTypes"
            :label="item.label + '(' + item.value + ')'"
            :value="item.value"
        />
      </el-select>
    </el-form-item>
    <el-form-item label="组件类型名称" required>
      <el-select v-model="formData.typeName" @change="handleTypeNameSelected" placeholder="先选择组件类型" filterable>
        <el-option
            v-for="item in currentTypeComponentOptions"
            :key="item.typeName"
            :label="item.typeName"
            :value="item.typeName"
        />
      </el-select>
    </el-form-item>
    <el-form-item label="组件名称">
      <el-input v-model="formData.name"/>
    </el-form-item>
    <el-form-item label="组件属性">
      <vue-form
          v-model="formData.props"
          :ui-schema="uiSchema"
          :schema="schema"
          :formFooter="{show:false}"
          :formProps="formProps"
      />
    </el-form-item>
  </el-form>
  <el-button type="primary" @click="onSubmit">确定</el-button>
</template>

<script setup lang="ts">
import VueForm from '@lljj/vue3-form-element';
import {reactive, ref} from 'vue';
import {ElInput} from "element-plus";
import {componentService} from "~/services/data.service";
import PairFormItem from "~/components/jsonschema/PairFormItem.vue";

const formData = reactive<ComponentForm>({});

const schema = ref({})
const uiSchema = ref({})
const currentTypeComponentOptions = ref<ComponentType[]>([])
const formProps = {
  inline: false,
  labelPosition: 'top',
  inlineFooter: false,
  layoutColumn: 1,
  labelWidth: 'auto'
}
const componentTypes = [
  {
    label: '触发器',
    value: 'TRIGGER'
  },
  {
    label: '数据源',
    value: 'SOURCE'
  },
  {
    label: '下载器',
    value: 'DOWNLOADER'
  },
  {
    label: '条目文件解析',
    value: 'ITEM_FILE_RESOLVER'
  },
  {
    label: '文件移动器',
    value: 'FILE_MOVER'
  },
  {
    label: '条目过滤',
    value: 'SOURCE_ITEM_FILTER'
  },
  {
    label: '条目内容过滤',
    value: 'ITEM_CONTENT_FILTER'
  },
  {
    label: '文件内容过滤',
    value: 'FILE_CONTENT_FILTER'
  },
  {
    label: '标签器',
    value: 'TAGGER',
  },
  {
    label: '文件替换规则',
    value: 'FILE_REPLACEMENT_DECIDER'
  },
  {
    label: '文件检测规则',
    value: 'FILE_EXISTS_DETECTOR',
  },
  {
    label: '变量提供',
    value: 'VARIABLE_PROVIDER'
  },
  {
    label: '变量替换',
    value: 'VARIABLE_REPLACER'
  },
  {
    label: '处理监听',
    value: 'PROCESS_LISTENER'
  }
]

function onSubmit() {
  console.log('提交数据', formData);
}

interface ComponentType {
  type: string;
  typeName: string;
}

const handleTypeSelected = async () => {
  if (formData.type) {
    const types = await componentService.types({'type': formData.type})
    currentTypeComponentOptions.value = types.data
  } else {
    currentTypeComponentOptions.value = []
  }
}

const handleTypeNameSelected = async () => {
  const typeName = formData.typeName
  const type = formData.type
  if (!typeName || !type) {
    return
  }
  const response = await componentService.getComponentPropSchema(type, typeName)
  if (response.data.propertySchema) {
    schema.value = response.data.propertySchema

    // 框架不支持直接渲染map类型的schema，需要特殊处理
    // 遍历schema如果type是object并且有additionalProperties type是string的话，就是一个map
    // 需要在uiSchema中设置ui:field为MapForm
    const resultSet: { [key: string]: { "ui:field": object } } = {};
    for (const key in schema.value.properties) {
      const property = schema.value.properties[key];
      if (property.type === 'object' && property.additionalProperties && property.additionalProperties.type === 'string') {
        resultSet[key] = {"ui:field": PairFormItem}
      }
    }
    console.log(resultSet)
    const merged = {
      ...resultSet,
      ...Object.keys(response.data.uiSchema).reduce((acc, key) => {
        acc[key] = { ...resultSet[key], ...response.data.uiSchema[key] };
        return acc;
      }, {} as Record<string, any>)
    };
    console.log(merged)
    uiSchema.value = merged;
  } else {
    schema.value = {}
  }
}


interface ComponentForm {
  name?: string;
  props?: any;
  type?: string;
  typeName?: string;
}
</script>
