// src/components/FileContentDetail.vue
<template>
  <el-descriptions :column="1">
    <el-descriptions-item label="下载路径:">{{ file?.fileDownloadPath }}</el-descriptions-item>
    <el-descriptions-item label="目标路径:">{{ `${file?.targetSavePath}/${file?.targetFilename}` }}
    </el-descriptions-item>
    <el-descriptions-item label="冲突路径:" v-if="file?.existTargetPath">{{ file?.existTargetPath }}
    </el-descriptions-item>
    <el-descriptions-item label="状态:">
      <el-tag size="large" :type="fileStatusOf(file?.status).type">
        {{ fileStatusOf(file?.status).label }}
      </el-tag>
    </el-descriptions-item>
    <el-descriptions-item label="URI:" v-if="file?.fileUri">
      <el-link type="info" :underline="false">{{ file?.fileUri }}</el-link>
    </el-descriptions-item>
    <el-descriptions-item label="模板:">
      <div>路径:{{ file?.fileSavePathPattern }}</div>
      <div>文件名:{{ file?.filenamePattern }}</div>
    </el-descriptions-item>
    <el-descriptions-item label="标签:" v-if="file?.tags?.length && file?.tags?.length > 0">
      <el-tag v-for="(tag, index) in file?.tags" :key="index">{{ tag }}</el-tag>
    </el-descriptions-item>
    <el-descriptions-item label="属性:" v-if="Object.keys(file?.attrs??{}).length > 0">
      <el-tag
          v-for="(attr, index) in file?.attrs" :key="index"
      >{{ index + ':' + attr }}
      </el-tag>
    </el-descriptions-item>
    <el-descriptions-item label="变量:" v-if="Object.keys(file?.patternVariables??{}).length > 0">
      <el-tag
          v-for="(v, index) in file?.patternVariables" :key="index"
      >{{ index + ':' + v }}
      </el-tag>
    </el-descriptions-item>
    <el-descriptions-item label="已处理变量:" v-if="Object.keys(file?.processedVariables??{}).length > 0">
      <el-tag
          v-for="(v, index) in file?.processedVariables" :key="index"
      >{{ index + ':' + v }}
      </el-tag>
    </el-descriptions-item>
    <el-descriptions-item label="错误:" v-if="file?.errors && file?.errors?.length > 0">
      <el-tag v-for="(error, index) in file?.errors" :key="index" type="danger">{{ error }}</el-tag>
    </el-descriptions-item>
  </el-descriptions>
</template>

<script setup lang="ts">
import {FileContent, fileStatusOf} from "~/services/data.service";

const props = defineProps<{ file?: FileContent | null }>();

</script>

// src/components/file-content-detail.tsx
import { Badge } from '@/components/ui/badge'
import { Descriptions, DescriptionsItem } from '@/components/shared/descriptions'
import type { FileContent } from '@/services/data.service'
import { fileStatusOf } from '@/services/data.service'

function statusVariant(type: string): 'default' | 'secondary' | 'destructive' | 'outline' {
  if (type === 'danger') return 'destructive'
  if (type === 'warning') return 'outline'
  if (type === 'info') return 'secondary'
  return 'default'
}

export function FileContentDetail({ file }: { file?: FileContent | null }) {
  const status = fileStatusOf(file?.status)

  return (
    <Descriptions>
      <DescriptionsItem label="下载路径:">{file?.fileDownloadPath}</DescriptionsItem>
      <DescriptionsItem label="目标路径:">{`${file?.targetSavePath ?? ''}/${file?.targetFilename ?? ''}`}</DescriptionsItem>
      {file?.existTargetPath ? <DescriptionsItem label="冲突路径:">{file.existTargetPath}</DescriptionsItem> : null}
      <DescriptionsItem label="状态:">
        <Badge variant={statusVariant(status.type)}>{status.label}</Badge>
      </DescriptionsItem>
      {file?.fileUri ? <DescriptionsItem label="URI:">{file.fileUri}</DescriptionsItem> : null}
      <DescriptionsItem label="模板:">
        <div>路径:{file?.fileSavePathPattern}</div>
        <div>文件名:{file?.filenamePattern}</div>
      </DescriptionsItem>
      {file?.tags?.length ? (
        <DescriptionsItem label="标签:">
          <div className="flex flex-wrap gap-1">
            {file.tags.map((tag) => (
              <Badge key={tag} variant="secondary">
                {tag}
              </Badge>
            ))}
          </div>
        </DescriptionsItem>
      ) : null}
      {Object.keys(file?.attrs ?? {}).length > 0 ? (
        <DescriptionsItem label="属性:">
          <div className="flex flex-wrap gap-1">
            {Object.entries(file?.attrs ?? {}).map(([key, attr]) => (
              <Badge key={key} variant="outline">
                {`${key}:${String(attr)}`}
              </Badge>
            ))}
          </div>
        </DescriptionsItem>
      ) : null}
      {Object.keys(file?.patternVariables ?? {}).length > 0 ? (
        <DescriptionsItem label="变量:">
          <div className="flex flex-wrap gap-1">
            {Object.entries(file?.patternVariables ?? {}).map(([key, val]) => (
              <Badge key={key} variant="outline">
                {`${key}:${String(val)}`}
              </Badge>
            ))}
          </div>
        </DescriptionsItem>
      ) : null}
      {Object.keys(file?.processedVariables ?? {}).length > 0 ? (
        <DescriptionsItem label="已处理变量:">
          <div className="flex flex-wrap gap-1">
            {Object.entries(file?.processedVariables ?? {}).map(([key, val]) => (
              <Badge key={key} variant="outline">
                {`${key}:${String(val)}`}
              </Badge>
            ))}
          </div>
        </DescriptionsItem>
      ) : null}
      {file?.errors?.length ? (
        <DescriptionsItem label="错误:">
          <div className="flex flex-wrap gap-1">
            {file.errors.map((error) => (
              <Badge key={error} variant="destructive">
                {error}
              </Badge>
            ))}
          </div>
        </DescriptionsItem>
      ) : null}
    </Descriptions>
  )
}
