// src/components/item-content-detail.tsx
import { Badge } from '~/components/ui/badge'
import { Descriptions, DescriptionsItem } from '~/components/shared/descriptions'
import type { ItemContent } from '~/services/data.service'

export function ItemContentDetail({ content }: { content?: ItemContent | null }) {
  const sourceItem = content?.sourceItem

  return (
    <Descriptions>
      <DescriptionsItem label="标题:">
        <div className="truncate" title={sourceItem?.title}>
          {sourceItem?.title}
        </div>
      </DescriptionsItem>
      <DescriptionsItem label="链接:">
        {sourceItem?.link ? (
          <a href={sourceItem.link} target="_blank" rel="noreferrer" className="break-all">
            {sourceItem.link}
          </a>
        ) : null}
      </DescriptionsItem>
      <DescriptionsItem label="时间:">{sourceItem?.datetime}</DescriptionsItem>
      <DescriptionsItem label="类型:">{sourceItem?.contentType}</DescriptionsItem>
      <DescriptionsItem label="下载链接:">
        <div className="truncate text-muted-foreground" title={sourceItem?.downloadUri}>
          {sourceItem?.downloadUri}
        </div>
      </DescriptionsItem>
      {sourceItem?.tags?.length ? (
        <DescriptionsItem label="标签:">
          <div className="flex flex-wrap gap-1">
            {sourceItem.tags.map((tag) => (
              <Badge key={tag} variant="secondary">
                {tag}
              </Badge>
            ))}
          </div>
        </DescriptionsItem>
      ) : null}
      {content && Object.keys(sourceItem?.attrs ?? {}).length > 0 ? (
        <DescriptionsItem label="属性:">
          <div className="flex flex-wrap gap-1">
            {Object.entries(sourceItem?.attrs ?? {}).map(([key, attr]) => (
              <Badge key={key} variant="outline">
                {`${key}:${String(attr)}`}
              </Badge>
            ))}
          </div>
        </DescriptionsItem>
      ) : null}
      {content && Object.keys(content.itemVariables ?? {}).length > 0 ? (
        <DescriptionsItem label="变量:">
          <div className="flex flex-wrap gap-1">
            {Object.entries(content.itemVariables ?? {}).map(([key, val]) => (
              <Badge key={key} variant="outline">
                {`${key}:${String(val)}`}
              </Badge>
            ))}
          </div>
        </DescriptionsItem>
      ) : null}
    </Descriptions>
  )
}

// src/components/ItemContentDetail.vue
<template>
  <el-descriptions :column="1">
    <el-descriptions-item label="标题:">{{ sourceItem?.title }}</el-descriptions-item>
    <el-descriptions-item label="链接:">
      <el-link type="primary" :href="sourceItem?.link" target="_blank" :underline="false">
        {{ sourceItem?.link }}
      </el-link>
    </el-descriptions-item>
    <el-descriptions-item label="时间:">{{ sourceItem?.datetime }}</el-descriptions-item>
    <el-descriptions-item label="类型:">{{ sourceItem?.contentType }}</el-descriptions-item>
    <el-descriptions-item label="下载链接:">
      <el-link type="info" :underline="false">{{ sourceItem?.downloadUri }}</el-link>
    </el-descriptions-item>
    <el-descriptions-item label="变量:" v-if="sourceItem?.tags?.length && sourceItem?.tags?.length > 0">
      <el-tag v-for="(tag, index) in sourceItem?.tags" :key="index">{{ tag }}</el-tag>
    </el-descriptions-item>
    <el-descriptions-item label="属性:" v-if="Object.keys(sourceItem?.attrs??{}).length > 0">
      <el-tag v-for="(attr, index) in sourceItem?.attrs" :key="index">
        {{ index + ':' + attr }}
      </el-tag>
    </el-descriptions-item>
    <el-descriptions-item label="变量:" v-if="Object.keys(content?.itemVariables??{}).length > 0">
      <el-tag v-for="(v, index) in content?.itemVariables" :key="index">
        {{ index + ':' + v }}
      </el-tag>
    </el-descriptions-item>
  </el-descriptions>
</template>

<script setup lang="ts">
import {ItemContent} from "~/services/data.service";

const props = defineProps<{ content?: ItemContent | null }>();
const sourceItem = props.content?.sourceItem
</script>
