// src/components/ProcessorForm.vue
<!--暂时不用数据驱动来渲染, 后续需要有比较多优化交互的体验不知道能不能实现-->
<template>
  <el-form :model="formValue" label-width="auto" style="max-width: 600px">
    <el-tabs tab-position="left" class="demo-tabs">
      <el-tab-pane label="基本">
        <el-form-item label="名称" required>
          <el-input v-model="formValue.name"/>
        </el-form-item>
        <el-form-item label="源" required>
          <ComponentSelector type="source" v-model="formValue.source"/>
        </el-form-item>
        <el-form-item label="触发器">
          <ComponentSelector type="trigger" :multiple="true" v-model="formValue.triggers"/>
        </el-form-item>
        <el-form-item label="文件解析器" required>
          <ComponentSelector type="itemFileResolver" v-model="formValue.itemFileResolver"/>
        </el-form-item>
        <el-form-item label="下载器" required>
          <ComponentSelector type="downloader" v-model="formValue.downloader"/>
        </el-form-item>
        <el-form-item label="移动器" required>
          <ComponentSelector type="fileMover" v-model="formValue.fileMover"/>
        </el-form-item>
        <el-form-item label="保存路径" required>
          <el-input v-model="formValue.savePath"/>
        </el-form-item>
        <el-form-item label="开启" required>
          <el-switch v-model="formValue.enabled"/>
        </el-form-item>
        <el-form-item label="类目">
          <el-input v-model="formValue.category"/>
        </el-form-item>
        <el-form-item label="标签">
          <DynamicTag v-model="formValue.tags"/>
        </el-form-item>
      </el-tab-pane>
      <el-tab-pane label="文件">
        <el-form-item label="目标路径模版">
          <el-input v-model="formValue.options.savePathPattern"/>
        </el-form-item>
        <el-form-item label="目标文件名模版">
          <el-input v-model="formValue.options.filenamePattern"/>
        </el-form-item>
        <el-form-item label="文件标签器">
          <ComponentSelector type="tagger" v-model="formValue.options.fileTaggers"/>
        </el-form-item>
        <el-form-item label="变量提供">
          <ComponentSelector type="variableProvider" :multiple="true" v-model="formValue.options.variableProviders"/>
        </el-form-item>
        <el-form-item label="变量替换">
          <ComponentSelector type="variableReplacer" v-model="formValue.options.variableReplacers"/>
        </el-form-item>
        <!--          TODO 不知道怎么展示-->
        <!--          <el-form-item label="正则替换变量">-->

        <!--          </el-form-item>-->
        <el-form-item label="变量错误策略">
          <el-select
              v-model="formValue.options.variableErrorStrategy"
              clearable
              placeholder="Select"
              style="width: 240px"
          >
            <el-option
                v-for="item in variableErrorStrategyOptions"
                :key="item.value"
                :label="item.label"
                :value="item.value"
            />
          </el-select>
        </el-form-item>
        <el-form-item label="变量冲突策略">
          <el-select
              v-model="formValue.options.variableConflictStrategy"
              clearable
              placeholder="Select"
              style="width: 240px"
          >
            <el-option
                v-for="item in variableConflictStrategyOptions"
                :key="item.value"
                :label="item.label"
                :value="item.value"
            />
          </el-select>
        </el-form-item>
        <el-form-item label="文件存在">
          <ComponentSelector type="fileExistsDetector" v-model="formValue.options.fileExistsDetector"/>
        </el-form-item>
        <el-form-item label="文件替换">
          <ComponentSelector type="fileReplacementDecider" v-model="formValue.options.fileReplacementDecider"/>
        </el-form-item>
        <el-form-item label="Windows路径字符替换">
          <el-switch v-model="formValue.options.supportWindowsPlatformPath"/>
        </el-form-item>
        <!--          TODO 不知道怎么展示-->
        <!--          <el-form-item label="文件分组">-->
        <!--          formValue.options.fileGrouping-->
        <!--          </el-form-item>-->
        <!--          <el-form-item label="条目分组">-->
        <!--          formValue.options.itemGrouping-->
        <!--          </el-form-item>-->
        <!--          <el-form-item label="变量处理">-->
        <!--          formValue.options.variableProcess-->
        <!--          </el-form-item>-->
      </el-tab-pane>
      <el-tab-pane label="过滤">
        <el-form-item label="条目过滤">
          <ComponentSelector type="sourceItemFilter" v-model="formValue.options.sourceItemFilters"/>
        </el-form-item>
        <el-form-item label="文件过滤">
          <ComponentSelector type="fileContentFilter" v-model="formValue.options.fileContentFilters"/>
        </el-form-item>
        <el-form-item label="条目内容过滤">
          <ComponentSelector type="itemContentFilter" v-model="formValue.options.itemContentFilters"/>
        </el-form-item>
        <el-form-item label="条目表达式排除">
          <!--            <el-input v-model="formValue.options.itemExpressionExclusions"/>-->
        </el-form-item>
        <el-form-item label="条目表达式包含">
          <!--            <el-input v-model="formValue.options.itemExpressionInclusions"/>-->
        </el-form-item>
        <el-form-item label="条目内容表达式排除">
          <!--            <el-input v-model="formValue.options.contentExpressionExclusions"/>-->
        </el-form-item>
        <el-form-item label="条目内容表达式包含">
          <!--            <el-input v-model="formValue.options.contentExpressionInclusions"/>-->
        </el-form-item>
        <el-form-item label="文件表达式排除">
          <!--            <el-input v-model="formValue.options.fileExpressionExclusions"/>-->
        </el-form-item>
        <el-form-item label="文件表达式包含">
          <!--            <el-input v-model="formValue.options.fileExpressionInclusions"/>-->
        </el-form-item>
      </el-tab-pane>
      <el-tab-pane label="处理">
        <el-form-item label="监听">
          <ComponentSelector type="process-listener" :multiple="true" v-model="formValue.options.processListeners"/>
        </el-form-item>
        <el-form-item label="重命名间隔">
          <el-input v-model="formValue.options.renameTaskInterval" placeholder="PT5M"/>
        </el-form-item>
        <el-form-item label="重命名次数阈值">
          <el-input-number v-model="formValue.options.renameTimesThreshold" placeholder="3"/>
        </el-form-item>
        <el-form-item label="保存处理内容">
          <el-switch v-model="formValue.options.saveProcessingContent"/>
        </el-form-item>
        <el-form-item label="条目获取数限制">
          <el-input-number v-model="formValue.options.fetchLimit" placeholder="50"/>
        </el-form-item>
        <el-form-item label="指针批量模式">
          <el-switch v-model="formValue.options.pointerBatchMode"/>
        </el-form-item>
        <el-form-item label="条目异常继续">
          <el-switch v-model="formValue.options.itemErrorContinue"/>
        </el-form-item>
        <el-form-item label="更新条目文件夹时间">
          <el-switch v-model="formValue.options.touchItemDirectory"/>
        </el-form-item>
        <el-form-item label="清理条目空文件夹">
          <el-switch v-model="formValue.options.deleteEmptyDirectory"/>
        </el-form-item>
        <el-form-item label="条目重试间隔毫秒">
          <el-input-number v-model="formValue.options.retryBackoffMills" :min="1" placeholder="5000"/>
        </el-form-item>
        <el-form-item label="并行数">
          <el-input-number v-model="formValue.options.parallelism" :min="1" :max="10" placeholder="1"/>
        </el-form-item>
        <el-form-item label="任务分组">
          <el-input v-model="formValue.options.taskGroup"/>
        </el-form-item>
      </el-tab-pane>
      <el-tab-pane label="下载">
        <el-form-item label="类目">
          <el-input v-model="formValue.options.downloadOptions.category"/>
        </el-form-item>
        <el-form-item label="标签">
          <DynamicTag v-model="formValue.options.downloadOptions.tags"/>
        </el-form-item>
        <el-form-item label="请求头">
          <!--            formValue.options.downloadOptions.headers-->
        </el-form-item>
      </el-tab-pane>
      <el-tab-pane label="其他">
        <el-form-item label="表达式类型">
          <el-select
              v-model="formValue.options.expression"
              clearable
              placeholder="CEL"
              style="width: 240px"
          >
            <el-option
                v-for="item in [{label:'CEL'},{label:'SPEL'}]"
                :key="item.label"
                :label="item.label"
                :value="item.label"
            />
          </el-select>
        </el-form-item>
      </el-tab-pane>
    </el-tabs>
  </el-form>
  <el-button type="primary" @click="onSubmit">确定</el-button>
</template>
<script setup lang="ts">
import {reactive, ref, toRefs} from 'vue'
import ComponentSelector from "~/components/ComponentSelector.vue";
import {ElInput} from "element-plus";

const props = defineProps<{
  processorName?: string,
}>();
const {processorName} = toRefs(props)

const formValue = reactive<ProcessorConfig>({
  enabled: true,
  options: {
    supportWindowsPlatformPath: true,
    saveProcessingContent: true,
    pointerBatchMode: true,
    touchItemDirectory: true,
    deleteEmptyDirectory: true,
    downloadOptions: {},
  }
});

const variableErrorStrategyOptions = [
  {label: '保留原有', value: 'ORIGINAL'},
  {label: '模板', value: 'PATTERN'},
  {label: '停留', value: 'STAY'},
  {label: '未解析', value: 'TO_UNRESOLVED'},
]
const variableConflictStrategyOptions = [
  {label: '任意', value: 'ANY'},
  {label: '值相同的数量最多的', value: 'VOTE'},
  {label: 'Provider定义的精度', value: 'ACCURACY'},
  {label: 'VOTE+SMART', value: 'SMART'},
]

interface ProcessorConfig {
  name?: string;
  triggers?: string[];
  source?: string;
  itemFileResolver?: string;
  downloader?: string;
  fileMover?: string;
  savePath?: string;
  options: Options;
  enabled?: boolean;
  category?: string | null;
  tags?: string[];
}

interface Options {
  variableProviders?: string[];
  sourceItemFilters?: string[];
  fileContentFilters?: string[];
  itemContentFilters?: string[];
  savePathPattern?: string;
  filenamePattern?: string;
  processListeners?: ListenerConfig[];
  renameTaskInterval?: number;
  downloadOptions: DownloadOptions;
  variableConflictStrategy?: string;
  renameTimesThreshold?: number;
  saveProcessingContent?: boolean;
  itemExpressionExclusions?: string[];
  itemExpressionInclusions?: string[];
  contentExpressionExclusions?: string[];
  contentExpressionInclusions?: string[];
  fileExpressionExclusions?: string[];
  fileExpressionInclusions?: string[];
  variableErrorStrategy?: string;
  touchItemDirectory?: boolean;
  deleteEmptyDirectory?: boolean;
  variableNameReplace?: { [key: string]: string };
  fileTaggers?: string[];
  regexVariableReplacers?: RegexVariableReplacer[];
  variableReplacers?: VariableReplacerConfig[];
  supportWindowsPlatformPath?: boolean;
  fileReplacementDecider?: string;
  fileExistsDetector?: string;
  fetchLimit?: number;
  pointerBatchMode?: boolean;
  itemErrorContinue?: boolean;
  fileGrouping?: FileGroupingConfig[];
  itemGrouping?: ItemGroupingConfig[];
  channelBufferSize?: number;
  recordMinimized?: boolean;
  parallelism?: number;
  retryBackoffMills?: number;
  taskGroup?: string;
  variableProcess?: { [key: string]: VariableProcessConfig };
  expression?: string;
}

interface FileGroupingConfig {
  tags?: string[];
  expressionMatching?: string | null;
  filenamePattern?: string | null;
  savePathPattern?: string | null;
  fileContentFilters?: string[] | null;
  fileExpressionExclusions?: string[] | null;
  fileExpressionInclusions?: string[] | null;
  fileReplacementDecider?: string | null;
}

interface ItemGroupingConfig {
  tags?: string[];
  expressionMatching?: string | null;
  filenamePattern?: string | null;
  savePathPattern?: string | null;
  variableProviders?: string[] | null;
  sourceItemFilters?: string[] | null;
  itemExpressionExclusions?: string[] | null;
  itemExpressionInclusions?: string[] | null;
}

interface VariableProcessConfig {
  chain?: string[];
  output: string;
}

interface ListenerConfig {
  id: string;
  mode: string;
}

interface VariableReplacerConfig {
  id: string;
  keys: string[]
}

interface RegexVariableReplacer {
  regex: string;
  replacement: string;
}

interface DownloadOptions {
  category?: string;
  tags?: string[];
  headers?: { [key: string]: string };
}

function onSubmit() {
  console.log('提交数据', formValue);
}
</script>

// src/components/processor-form.tsx
import { useState } from 'react'

import { ComponentSelector } from '@/components/component-selector'
import { DynamicTag } from '@/components/dynamic-tag'
import { FormRow } from '@/components/shared/form-row'
import { Button } from '@/components/ui/button'
import { Input } from '@/components/ui/input'
import { Switch } from '@/components/ui/switch'
import { Tabs, TabsContent, TabsList, TabsTrigger } from '@/components/ui/tabs'
import { SingleSelect } from '@/components/shared/multi-select'

interface ProcessorConfig {
  name?: string
  triggers?: string[]
  source?: string
  itemFileResolver?: string
  downloader?: string
  fileMover?: string
  savePath?: string
  options: Options
  enabled?: boolean
  category?: string | null
  tags?: string[]
}

interface Options {
  variableProviders?: string[]
  sourceItemFilters?: string[]
  fileContentFilters?: string[]
  itemContentFilters?: string[]
  savePathPattern?: string
  filenamePattern?: string
  processListeners?: string[]
  renameTaskInterval?: number | string
  downloadOptions: DownloadOptions
  variableConflictStrategy?: string
  renameTimesThreshold?: number | string
  saveProcessingContent?: boolean
  itemExpressionExclusions?: string[]
  itemExpressionInclusions?: string[]
  contentExpressionExclusions?: string[]
  contentExpressionInclusions?: string[]
  fileExpressionExclusions?: string[]
  fileExpressionInclusions?: string[]
  variableErrorStrategy?: string
  touchItemDirectory?: boolean
  deleteEmptyDirectory?: boolean
  fileTaggers?: string[]
  variableReplacers?: string[]
  supportWindowsPlatformPath?: boolean
  fileReplacementDecider?: string
  fileExistsDetector?: string
  fetchLimit?: number | string
  pointerBatchMode?: boolean
  itemErrorContinue?: boolean
  parallelism?: number | string
  retryBackoffMills?: number | string
  taskGroup?: string
  expression?: string
}

interface DownloadOptions {
  category?: string
  tags?: string[]
}

const variableErrorStrategyOptions = [
  { label: '保留原有', value: 'ORIGINAL' },
  { label: '模板', value: 'PATTERN' },
  { label: '停留', value: 'STAY' },
  { label: '未解析', value: 'TO_UNRESOLVED' },
]

const variableConflictStrategyOptions = [
  { label: '任意', value: 'ANY' },
  { label: '值相同的数量最多的', value: 'VOTE' },
  { label: 'Provider定义的精度', value: 'ACCURACY' },
  { label: 'VOTE+SMART', value: 'SMART' },
]

const expressionOptions = [
  { label: 'CEL', value: 'CEL' },
  { label: 'SPEL', value: 'SPEL' },
]

export function ProcessorForm() {
  const [formValue, setFormValue] = useState<ProcessorConfig>({
    enabled: true,
    options: {
      supportWindowsPlatformPath: true,
      saveProcessingContent: true,
      pointerBatchMode: true,
      touchItemDirectory: true,
      deleteEmptyDirectory: true,
      downloadOptions: {},
    },
  })

  const updateRoot = <K extends keyof ProcessorConfig>(key: K, value: ProcessorConfig[K]) => {
    setFormValue((current) => ({ ...current, [key]: value }))
  }

  const updateOptions = <K extends keyof Options>(key: K, value: Options[K]) => {
    setFormValue((current) => ({ ...current, options: { ...current.options, [key]: value } }))
  }

  const updateDownloadOptions = <K extends keyof DownloadOptions>(key: K, value: DownloadOptions[K]) => {
    setFormValue((current) => ({ ...current, options: { ...current.options, downloadOptions: { ...current.options.downloadOptions, [key]: value } } }))
  }

  return (
    <div className="space-y-4">
      <Tabs defaultValue="basic" className="w-full">
        <TabsList className="grid w-full grid-cols-3 gap-1 md:grid-cols-6">
          <TabsTrigger value="basic">基本</TabsTrigger>
          <TabsTrigger value="file">文件</TabsTrigger>
          <TabsTrigger value="filter">过滤</TabsTrigger>
          <TabsTrigger value="process">处理</TabsTrigger>
          <TabsTrigger value="download">下载</TabsTrigger>
          <TabsTrigger value="other">其他</TabsTrigger>
        </TabsList>

        <TabsContent value="basic" className="grid gap-4">
          <FormRow label="名称" required>
            <Input value={formValue.name ?? ''} onChange={(event) => updateRoot('name', event.target.value)} />
          </FormRow>
          <FormRow label="源" required>
            <ComponentSelector type="source" value={formValue.source} onChange={(next) => updateRoot('source', typeof next === 'string' ? next : undefined)} />
          </FormRow>
          <FormRow label="触发器">
            <ComponentSelector type="trigger" multiple value={formValue.triggers ?? []} onChange={(next) => updateRoot('triggers', Array.isArray(next) ? next : [])} />
          </FormRow>
          <FormRow label="文件解析器" required>
            <ComponentSelector type="itemFileResolver" value={formValue.itemFileResolver} onChange={(next) => updateRoot('itemFileResolver', typeof next === 'string' ? next : undefined)} />
          </FormRow>
          <FormRow label="下载器" required>
            <ComponentSelector type="downloader" value={formValue.downloader} onChange={(next) => updateRoot('downloader', typeof next === 'string' ? next : undefined)} />
          </FormRow>
          <FormRow label="移动器" required>
            <ComponentSelector type="fileMover" value={formValue.fileMover} onChange={(next) => updateRoot('fileMover', typeof next === 'string' ? next : undefined)} />
          </FormRow>
          <FormRow label="保存路径" required>
            <Input value={formValue.savePath ?? ''} onChange={(event) => updateRoot('savePath', event.target.value)} />
          </FormRow>
          <FormRow label="开启" required>
            <Switch checked={Boolean(formValue.enabled)} onCheckedChange={(checked) => updateRoot('enabled', checked)} />
          </FormRow>
          <FormRow label="类目">
            <Input value={formValue.category ?? ''} onChange={(event) => updateRoot('category', event.target.value)} />
          </FormRow>
          <FormRow label="标签">
            <DynamicTag value={formValue.tags ?? []} onChange={(next) => updateRoot('tags', next)} />
          </FormRow>
        </TabsContent>

        <TabsContent value="file" className="grid gap-4">
          <FormRow label="目标路径模版">
            <Input value={String(formValue.options.savePathPattern ?? '')} onChange={(event) => updateOptions('savePathPattern', event.target.value)} />
          </FormRow>
          <FormRow label="目标文件名模版">
            <Input value={String(formValue.options.filenamePattern ?? '')} onChange={(event) => updateOptions('filenamePattern', event.target.value)} />
          </FormRow>
          <FormRow label="文件标签器">
            <ComponentSelector type="tagger" multiple value={formValue.options.fileTaggers ?? []} onChange={(next) => updateOptions('fileTaggers', Array.isArray(next) ? next : [])} />
          </FormRow>
          <FormRow label="变量提供">
            <ComponentSelector type="variableProvider" multiple value={formValue.options.variableProviders ?? []} onChange={(next) => updateOptions('variableProviders', Array.isArray(next) ? next : [])} />
          </FormRow>
          <FormRow label="变量替换">
            <ComponentSelector type="variableReplacer" multiple value={formValue.options.variableReplacers ?? []} onChange={(next) => updateOptions('variableReplacers', Array.isArray(next) ? next : [])} />
          </FormRow>
          <FormRow label="变量错误策略">
            <SingleSelect options={variableErrorStrategyOptions} value={formValue.options.variableErrorStrategy} onChange={(next) => updateOptions('variableErrorStrategy', next)} placeholder="Select" />
          </FormRow>
          <FormRow label="变量冲突策略">
            <SingleSelect options={variableConflictStrategyOptions} value={formValue.options.variableConflictStrategy} onChange={(next) => updateOptions('variableConflictStrategy', next)} placeholder="Select" />
          </FormRow>
          <FormRow label="文件存在">
            <ComponentSelector type="fileExistsDetector" value={formValue.options.fileExistsDetector} onChange={(next) => updateOptions('fileExistsDetector', typeof next === 'string' ? next : undefined)} />
          </FormRow>
          <FormRow label="文件替换">
            <ComponentSelector type="fileReplacementDecider" value={formValue.options.fileReplacementDecider} onChange={(next) => updateOptions('fileReplacementDecider', typeof next === 'string' ? next : undefined)} />
          </FormRow>
          <FormRow label="Windows路径字符替换">
            <Switch checked={Boolean(formValue.options.supportWindowsPlatformPath)} onCheckedChange={(checked) => updateOptions('supportWindowsPlatformPath', checked)} />
          </FormRow>
        </TabsContent>

        <TabsContent value="filter" className="grid gap-4">
          <FormRow label="条目过滤">
            <ComponentSelector type="sourceItemFilter" multiple value={formValue.options.sourceItemFilters ?? []} onChange={(next) => updateOptions('sourceItemFilters', Array.isArray(next) ? next : [])} />
          </FormRow>
          <FormRow label="文件过滤">
            <ComponentSelector type="fileContentFilter" multiple value={formValue.options.fileContentFilters ?? []} onChange={(next) => updateOptions('fileContentFilters', Array.isArray(next) ? next : [])} />
          </FormRow>
          <FormRow label="条目内容过滤">
            <ComponentSelector type="itemContentFilter" multiple value={formValue.options.itemContentFilters ?? []} onChange={(next) => updateOptions('itemContentFilters', Array.isArray(next) ? next : [])} />
          </FormRow>
          <FormRow label="条目表达式排除" />
          <FormRow label="条目表达式包含" />
          <FormRow label="条目内容表达式排除" />
          <FormRow label="条目内容表达式包含" />
          <FormRow label="文件表达式排除" />
          <FormRow label="文件表达式包含" />
        </TabsContent>

        <TabsContent value="process" className="grid gap-4">
          <FormRow label="监听">
            <ComponentSelector type="process-listener" multiple value={formValue.options.processListeners ?? []} onChange={(next) => updateOptions('processListeners', Array.isArray(next) ? next : [])} />
          </FormRow>
          <FormRow label="重命名间隔">
            <Input value={String(formValue.options.renameTaskInterval ?? '')} onChange={(event) => updateOptions('renameTaskInterval', event.target.value)} placeholder="PT5M" />
          </FormRow>
          <FormRow label="重命名次数阈值">
            <Input type="number" value={String(formValue.options.renameTimesThreshold ?? '')} onChange={(event) => updateOptions('renameTimesThreshold', event.target.value)} placeholder="3" />
          </FormRow>
          <FormRow label="保存处理内容">
            <Switch checked={Boolean(formValue.options.saveProcessingContent)} onCheckedChange={(checked) => updateOptions('saveProcessingContent', checked)} />
          </FormRow>
          <FormRow label="条目获取数限制">
            <Input type="number" value={String(formValue.options.fetchLimit ?? '')} onChange={(event) => updateOptions('fetchLimit', event.target.value)} placeholder="50" />
          </FormRow>
          <FormRow label="指针批量模式">
            <Switch checked={Boolean(formValue.options.pointerBatchMode)} onCheckedChange={(checked) => updateOptions('pointerBatchMode', checked)} />
          </FormRow>
          <FormRow label="条目异常继续">
            <Switch checked={Boolean(formValue.options.itemErrorContinue)} onCheckedChange={(checked) => updateOptions('itemErrorContinue', checked)} />
          </FormRow>
          <FormRow label="更新条目文件夹时间">
            <Switch checked={Boolean(formValue.options.touchItemDirectory)} onCheckedChange={(checked) => updateOptions('touchItemDirectory', checked)} />
          </FormRow>
          <FormRow label="清理条目空文件夹">
            <Switch checked={Boolean(formValue.options.deleteEmptyDirectory)} onCheckedChange={(checked) => updateOptions('deleteEmptyDirectory', checked)} />
          </FormRow>
          <FormRow label="条目重试间隔毫秒">
            <Input type="number" min={1} value={String(formValue.options.retryBackoffMills ?? '')} onChange={(event) => updateOptions('retryBackoffMills', event.target.value)} placeholder="5000" />
          </FormRow>
          <FormRow label="并行数">
            <Input type="number" min={1} max={10} value={String(formValue.options.parallelism ?? '')} onChange={(event) => updateOptions('parallelism', event.target.value)} placeholder="1" />
          </FormRow>
          <FormRow label="任务分组">
            <Input value={String(formValue.options.taskGroup ?? '')} onChange={(event) => updateOptions('taskGroup', event.target.value)} />
          </FormRow>
        </TabsContent>

        <TabsContent value="download" className="grid gap-4">
          <FormRow label="类目">
            <Input value={String(formValue.options.downloadOptions.category ?? '')} onChange={(event) => updateDownloadOptions('category', event.target.value)} />
          </FormRow>
          <FormRow label="标签">
            <DynamicTag value={formValue.options.downloadOptions.tags ?? []} onChange={(next) => updateDownloadOptions('tags', next)} />
          </FormRow>
          <FormRow label="请求头" />
        </TabsContent>

        <TabsContent value="other" className="grid gap-4">
          <FormRow label="表达式类型">
            <SingleSelect options={expressionOptions} value={formValue.options.expression} onChange={(next) => updateOptions('expression', next)} placeholder="CEL" />
          </FormRow>
        </TabsContent>
      </Tabs>

      <Button type="button" onClick={() => console.log('提交数据', formValue)}>
        确定
      </Button>
    </div>
  )
}
