// src/components/ProcessorSelector.vue
<template>
  <el-select
      v-model="selected"
      multiple
      collapse-tags
      collapse-tags-tooltip
      :max-collapse-tags="3"
      placeholder="筛选处理器"
      filterable
      @focus="fetchProcessors"
  >
    <el-option
        v-for="item in processors"
        :key="item"
        :label="item"
        :value="item"
    />
  </el-select>
</template>

<script setup lang="ts">
import {ref, watch} from 'vue'
import {processorService} from "~/services/data.service";

const selected = ref<string[]>([])
const processors = ref<string[]>([])

const fetchProcessors = async () => {
  processorService.query().then(response => {
    processors.value = response.map(item => {
      return item.name
    })
  })
}


const emit = defineEmits(['update:selected'])
watch(selected, (newValue) => {
  emit('update:selected', newValue);
});
</script>

// src/components/processor-selector.tsx
import { useState } from 'react'

import { MultiSelect } from '~/components/shared/multi-select'
import { processorService } from '~/services/data.service'

export function ProcessorSelector({ value, onChange }: { value: string[]; onChange: (next: string[]) => void }) {
  const [options, setOptions] = useState<{ label: string; value: string }[]>([])

  const fetchProcessors = async () => {
    if (options.length > 0) {
      return
    }
    const processors = await processorService.query()
    setOptions(processors.map((item) => ({ label: item.name, value: item.name })))
  }

  return (
    <div onClick={fetchProcessors}>
      <MultiSelect options={options} value={value} onChange={onChange} placeholder="筛选处理器" />
    </div>
  )
}
