// src/components/processor-dry-run.tsx
import { useState } from 'react'

import { FileContentDetail } from '~/components/file-content-detail'
import { ItemContentDetail } from '~/components/item-content-detail'
import { JsonEditor } from '~/components/shared/json-editor'
import { Badge } from '~/components/ui/badge'
import { Button } from '~/components/ui/button'
import { Dialog, DialogContent, DialogHeader, DialogTitle } from '~/components/ui/dialog'
import { Switch } from '~/components/ui/switch'
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from '~/components/ui/table'
import {
  type FileContent,
  fileStatusGrouping,
  itemStatusOf,
  type ProcessingContent,
  processorService,
} from '~/services/data.service'

function statusVariant(type: string): 'default' | 'secondary' | 'destructive' | 'outline' {
  if (type === 'danger') return 'destructive'
  if (type === 'warning') return 'outline'
  if (type === 'info') return 'secondary'
  return 'default'
}

async function* makeStreamLineIterator(readerStream: ReadableStream<Uint8Array>, terminateSignal: () => boolean) {
  const reader = readerStream.getReader()
  let { value: chunk, done: readerDone } = await reader.read()
  const utf8Decoder = new TextDecoder('utf-8')
  let partialLine = chunk ? utf8Decoder.decode(chunk, { stream: true }) : ''

  const re = /\r\n|\n|\r/gm
  let startIndex = 0
  for (;;) {
    if (terminateSignal()) {
      await reader.cancel('terminate signal received')
      break
    }

    const result = re.exec(partialLine)
    if (!result) {
      if (readerDone) {
        break
      }
      const remainder = partialLine.substring(startIndex)
      ;({ value: chunk, done: readerDone } = await reader.read())
      partialLine = remainder + (chunk ? utf8Decoder.decode(chunk, { stream: true }) : '')
      startIndex = re.lastIndex = 0
      continue
    }
    yield partialLine.substring(startIndex, result.index)
    startIndex = re.lastIndex
  }
  if (startIndex < partialLine.length) {
    yield partialLine.substring(startIndex)
  }
}

export function ProcessorDryRun({ processorName }: { processorName?: string }) {
  const [dryRunFormData, setDryRunFormData] = useState({ filterProcessed: true, pointer: '{}' })
  const [streamable, setStreamable] = useState(true)
  const [loading, setLoading] = useState(false)
  const [dryRunOpened, setDryRunOpened] = useState(false)
  const [dryRunResult, setDryRunResult] = useState<ProcessingContent[]>([])
  const [fileContents, setFileContents] = useState<FileContent[]>([])
  const [showFileContentDialog, setShowFileContentDialog] = useState(false)

  const handleDryRunFormSubmit = async () => {
    if (!processorName) {
      return
    }
    setDryRunOpened(true)
    setDryRunResult([])
    setLoading(true)

    const payload = {
      filterProcessed: dryRunFormData.filterProcessed,
      pointer: dryRunFormData.pointer.trim() ? JSON.parse(dryRunFormData.pointer) : null,
    }

    if (!streamable) {
      const response = await processorService.dryRun(processorName, payload).finally(() => setLoading(false))
      setDryRunResult(response.data)
      return
    }

    const response = await processorService.dryRunStream(processorName, payload)
    const body = response.body
    if (!body) {
      setLoading(false)
      return
    }

    let firstLineFlag = true
    for await (const line of makeStreamLineIterator(body, () => !dryRunOpened)) {
      if (firstLineFlag) {
        setLoading(false)
        firstLineFlag = false
      }
      try {
        const content = JSON.parse(line) as ProcessingContent
        setDryRunResult((current) => [...current, content])
      } catch {
        console.warn('Failed to parse line:', line)
      }
    }
    setLoading(false)
  }

  return (
    <div className="space-y-4">
      <div className="grid gap-4">
        <div className="flex items-center justify-between rounded-md border p-3">
          <span className="text-sm">过滤已处理的Item</span>
          <Switch checked={dryRunFormData.filterProcessed} onCheckedChange={(checked) => setDryRunFormData((current) => ({ ...current, filterProcessed: checked }))} />
        </div>
        <div className="grid gap-2">
          <div className="text-sm font-medium">Pointer</div>
          <JsonEditor value={dryRunFormData.pointer} onChange={(value) => setDryRunFormData((current) => ({ ...current, pointer: value }))} />
        </div>
        <div className="flex items-center justify-between rounded-md border p-3">
          <span className="text-sm">流式响应</span>
          <Switch checked={streamable} onCheckedChange={setStreamable} />
        </div>
        <Button onClick={handleDryRunFormSubmit}>确认</Button>
      </div>

      <Dialog open={dryRunOpened} onOpenChange={(open) => {
        setDryRunOpened(open)
        if (!open) {
          setDryRunResult([])
        }
      }}>
        <DialogContent className="max-w-6xl">
          <DialogHeader>
            <DialogTitle>Dry Run</DialogTitle>
          </DialogHeader>
          <div className="max-h-[70vh] overflow-auto rounded-md border">
            <Table>
              <TableHeader>
                <TableRow>
                  <TableHead>Hash</TableHead>
                  <TableHead>条目</TableHead>
                  <TableHead>文件</TableHead>
                </TableRow>
              </TableHeader>
              <TableBody>
                {dryRunResult.map((row) => {
                  const status = itemStatusOf(row.status)
                  return (
                    <TableRow key={`${row.itemHash}-${row.id ?? 'dry-run'}`}>
                      <TableCell>
                        <div className="flex flex-col gap-2">
                          <Badge variant={statusVariant(status.type)}>状态:{status.label}</Badge>
                          <Badge variant="secondary">Hash:{row.itemHash}</Badge>
                        </div>
                      </TableCell>
                      <TableCell className="min-w-[360px]">
                        <ItemContentDetail content={row.itemContent} />
                      </TableCell>
                      <TableCell>
                        <div className="flex flex-col gap-2">
                          <Button variant="outline" size="sm" onClick={() => {
                            setFileContents(row.itemContent.fileContents)
                            setShowFileContentDialog(true)
                          }}>
                            查看{row.itemContent.fileContents.length}个文件
                          </Button>
                          {Array.from(fileStatusGrouping(row.itemContent.fileContents)).map(([groupStatus, count]) => (
                            <Badge key={groupStatus.value} variant={statusVariant(groupStatus.type)}>
                              {groupStatus.label}:{count}
                            </Badge>
                          ))}
                        </div>
                      </TableCell>
                    </TableRow>
                  )
                })}
              </TableBody>
            </Table>
            {loading ? <div className="p-4 text-sm text-muted-foreground">加载中...</div> : null}
          </div>
        </DialogContent>
      </Dialog>

      <Dialog open={showFileContentDialog} onOpenChange={setShowFileContentDialog}>
        <DialogContent className="max-w-5xl">
          <DialogHeader>
            <DialogTitle>文件内容</DialogTitle>
          </DialogHeader>
          <div className="max-h-[70vh] space-y-4 overflow-auto">
            {fileContents.map((file) => (
              <div key={file.fileDownloadPath} className="rounded-md border p-4">
                <FileContentDetail file={file} />
              </div>
            ))}
          </div>
        </DialogContent>
      </Dialog>
    </div>
  )
}

// src/components/ProcessorDryRun.vue
<template>
  <el-form :model="dryRunFormData" label-width="auto">
    <el-form-item label="过滤已处理的Item">
      <el-switch v-model="dryRunFormData.filterProcessed"/>
    </el-form-item>
    <el-form-item label="Pointer">
      <json-editor
          v-model="dryRunFormData.pointer"
          mode="tree"
          :ask-to-format="false"
          :darkTheme="isDark"/>
    </el-form-item>
    <el-form-item label="流式响应">
      <el-switch v-model="streamable"/>
    </el-form-item>
    <el-form-item>
      <el-button type="primary" @click="handleDryRunFormSubmit">确认</el-button>
    </el-form-item>
  </el-form>

  <el-dialog v-model="dryRunOpened" @close="() => dryRunResult = []">
    <el-table
        :data="dryRunResult"
        row-key="itemHash"
        style="width: 100%;"
        v-loading="loading"
    >
      <el-table-column prop="itemHash" width="auto">
        <template #default="scope">
          <el-tag size="large" :type="itemStatusOf(scope.row.status).type">
            状态:{{ itemStatusOf(scope.row.status).label }}
          </el-tag>
          <el-tag size="large" type="info">Hash:{{ scope.row.itemHash }}</el-tag>
        </template>
      </el-table-column>
      <el-table-column prop="itemContent.sourceItem.title" label="条目" min-width="300" width="auto">
        <template #default="scope">
          <ItemContentDetail :content="scope.row.itemContent"/>
        </template>
      </el-table-column>
      <el-table-column prop="itemContent.fileContents.length" label="文件">
        <template #default="scope">
          <el-button size="small" @click="handleFileContentOpen(scope.row)">
            查看{{ scope.row.itemContent.fileContents.length }}个文件
          </el-button>
          <el-tag
              v-for="[status, count] in fileStatusGrouping(scope.row.itemContent.fileContents)"
              :key="status.value" :type="status.type"
          >
            {{ status.label }}:{{ count }}
          </el-tag>
        </template>
      </el-table-column>
    </el-table>
  </el-dialog>

  <el-dialog v-model="showFileContentDialog">
    <el-table :data="fileContents" row-key="fileDownloadPath">
      <el-table-column>
        <template #default="scope">
          <FileContentDetail :file="scope.row"/>
        </template>
      </el-table-column>
    </el-table>
  </el-dialog>
</template>

<script setup lang="ts">
import {isDark} from "~/composables";
import JsonEditor from "vue3-ts-jsoneditor";
import {ElButton, ElSwitch} from "element-plus";
import {
  FileContent,
  fileStatusGrouping,
  ItemContent,
  itemStatusOf,
  ProcessingContent,
  processorService
} from "~/services/data.service";
import {reactive, ref, toRefs} from "vue";
import ItemContentDetail from "~/components/ItemContentDetail.vue";

const props = defineProps<{
  processorName?: string,
}>();

const dryRunFormData = reactive({
  filterProcessed: true,
  pointer: null
})
const streamable = ref(true)

const {processorName} = toRefs(props)

const loading = ref(false)
const handleDryRunFormSubmit = async () => {
  if (!processorName.value) {
    return
  }
  dryRunOpened.value = true
  loading.value = true
  if (!streamable.value) {
    const response = await processorService.dryRun(processorName.value, dryRunFormData)
        .finally(() => {
          loading.value = false
        })
    dryRunResult.value = response.data
    return
  }

  const response = await processorService.dryRunStream(processorName.value, dryRunFormData)
  const body = response.body
  if (!body) {
    return
  }

  let firstLineFlag = true
  for await (const line of makeStreamLineIterator(response.body, () => !dryRunOpened.value)) {
    if (firstLineFlag) {
      loading.value = false
      firstLineFlag = false
    }
    updateDryRunTable(line)
  }
  loading.value = false
};

async function* makeStreamLineIterator(
    readerStream: ReadableStream<Uint8Array>,
    terminateSignal: () => boolean
) {
  const reader = readerStream.getReader();
  let {value: chunk, done: readerDone} = await reader.read();
  const utf8Decoder = new TextDecoder('utf-8');
  let partialLine = chunk ? utf8Decoder.decode(chunk, {stream: true}) : '';

  const re = /\r\n|\n|\r/gm;
  let startIndex = 0;
  for (; ;) {
    if (terminateSignal()) {
      await reader.cancel('terminate signal received')
      break
    }

    let result = re.exec(partialLine);
    if (!result) {
      if (readerDone) {
        break;
      }
      let remainder = partialLine.substring(startIndex);
      ({value: chunk, done: readerDone} = await reader.read());
      partialLine = remainder + (chunk ? utf8Decoder.decode(chunk, {stream: true}) : '');
      startIndex = re.lastIndex = 0;
      continue;
    }
    yield partialLine.substring(startIndex, result.index);
    startIndex = re.lastIndex;
  }
  if (startIndex < partialLine.length) {
    yield partialLine.substring(startIndex);
  }
}

const updateDryRunTable = (json: string) => {
  try {
    const content = JSON.parse(json)
    dryRunResult.value.push(content)
  } catch (e) {
    console.warn('Failed to parse line:', json);
  }
}

// result
const dryRunOpened = ref(false)
const dryRunResult = ref<ItemContent[]>([])

const fileContents = ref<FileContent[]>([]);
const showFileContentDialog = ref(false);
const handleFileContentOpen = (content: ProcessingContent) => {
  fileContents.value = content.itemContent.fileContents;
  showFileContentDialog.value = true;
}
</script>
