// src/components/component-selector.tsx
import { useState } from 'react'

import { MultiSelect, SingleSelect } from '@/components/shared/multi-select'
import { componentService } from '@/services/data.service'

export function ComponentSelector({
  type,
  multiple,
  value,
  onChange,
}: {
  type: string
  multiple?: boolean
  value?: string | string[]
  onChange: (next: string | string[] | undefined) => void
}) {
  const [options, setOptions] = useState<{ label: string; value: string }[]>([])

  const loadOptions = async () => {
    if (options.length > 0) {
      return
    }
    const components = await componentService.query({ type })
    setOptions(
      components.map((component) => {
        const componentId = component.typeName === component.name ? component.typeName : `${component.typeName}:${component.name}`
        return {
          label: componentId,
          value: componentId,
        }
      }),
    )
  }

  return (
    <div onClick={loadOptions}>
      {multiple ? (
        <MultiSelect options={options} value={Array.isArray(value) ? value : []} onChange={(next) => onChange(next)} placeholder="选择组件ID" />
      ) : (
        <SingleSelect options={options} value={typeof value === 'string' ? value : undefined} onChange={(next) => onChange(next)} placeholder="选择组件ID" />
      )}
    </div>
  )
}

// src/views/biz/ComponentSelector.vue
<template>
  <el-select
      v-model="componentValue"
      filterable
      clearable
      style="width: 240px"
      :multiple="multiple"
      @focus="loadOptions"
      placeholder="选择组件ID"
  >
    <el-option
        v-for="item in options"
        :key="item.value"
        :label="item.label"
        :value="item.value"
    />
  </el-select>
</template>

<script setup lang="ts">
import {ref, toRefs} from "vue";
import {componentService} from "~/services/data.service";

const props = defineProps<{
  type: string,
  multiple?: boolean,
}>()
const {type, multiple} = toRefs(props)
const options = ref()
const componentValue = ref<string | string[]>()

const loadOptions = async () => {
  if (options.value) {
    return
  }
  const components = await componentService.query({'type': type.value})
  options.value = components.map((component) => {
    let componentId = (component.typeName === component.name) ? component.typeName : component.typeName + ':' + component.name
    return {
      label: componentId,
      value: componentId
    }
  })
}

</script>
